apiVersion: v2
appVersion: "0.0.1"
description: Chart for Oral History Public-Facing App
name: oralhistory
version: 0.0.3

dependencies:
  - name: postgresql
    # This is the chart version, not the image version.
    # TODO: Be sure chart versions here are compatible with image verions in values files.
    version: 12.2.5
    repository: https://raw.githubusercontent.com/bitnami/charts/archive-full-index/bitnami
    condition: postgresql.enabled
  - name: solr
    # This is the chart version, not the image version.
    # TODO: Be sure chart versions here are compatible with image verions in values files.
    version: 7.2.1
    repository: https://raw.githubusercontent.com/bitnami/charts/archive-full-index/bitnami
    condition: solr.enabled