# Values file for oralhistoryprod
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: uclalibrary/oral-history
  tag: v1.0.0
  pullPolicy: Always

# Chart documentation: https://github.com/bitnami/charts/tree/main/bitnami/solr
solr:
  enabled: true
  image:
    repository: bitnami/solr
    tag: 8.11.1
  auth:
    enabled: true
    adminUsername: admin
  coreName: blacklight
  collection: blacklight-core
  persistence:
    enabled: true
    storageClass: "vsphere-csi-sc"
    size: 8Gi
    mountPath: /bitnami/solr

# Chart documentation: https://github.com/bitnami/charts/tree/main/bitnami/postgresql
postgresql:
  enabled: true
  image:
    repository: bitnami/postgresql
    tag: 12.3.0
  auth:
    username: blacklight
    database: blacklight
  service:
    ports:
      postgresql: 5432

externalSecrets:
  refreshInterval: 10m
  secretStoreRef:
    name: systems-clustersecretstore
    kind: ClusterSecretStore
  env:
    negativeCaptchaSecret: negative-captcha-external-secret/negative-captcha-secret
    databasePassword: database-external-password/database-password
    solrAdminPassword: solr-external-password/solr-admin-password

# configure a registry token for access to your container registry, needs read permissions, create secret in Rancher, follow instructions:
# https://ranchermanager.docs.rancher.com/v2.5/how-to-guides/new-user-guides/kubernetes-resources-setup/kubernetes-and-docker-registries#creating-a-registry
# replace registry-token below with the name of the secret you created in the Rancher UI
imagePullSecrets: []
  # - registry-token
fullnameOverride: "oral-history"

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: "true"
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
    cert-manager.io/cluster-issuer: sectigo-acme-clusterissuer
    kubernetes.io/tls-acme: "true"

  hosts:
    - host: oralhistory.library.ucla.edu
      paths:
        - "/"

  tls:
   - secretName: oralhistory-tls
     hosts:
       - oralhistory.library.ucla.edu

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
