image: registry.gitlab.com/notch8/scripts/builder:latest
services:
  - docker:dind
  - postgres:latest
  - solr:latest

stages:
  - build

variables:
  POSTGRES_DB: oral_history
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: password
  POSTGRES_HOST: postgres
  TEST_DB: oral_history
  DOCKER_DRIVER: overlay

before_script:
  - export TAG=${CI_COMMIT_SHA:0:8}
  - export REGISTRY_HOST=${CI_REGISTRY}
  - export REGISTRY_URI="/${CI_PROJECT_PATH}"
  - touch .env.development
  - touch .env.production

build:
  stage: build
  script:
    - docker login -u "gitlab-ci-token" -p "$CI_JOB_TOKEN" $CI_REGISTRY
    - sc build
    - sc push
    - docker tag $CI_REGISTRY_IMAGE:$TAG $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME
  tags:
    - docker
