image: docker:17.04
services:
  - docker:dind
  - postgres:latest
  - solr:latest

stages:
  - build
  - test
  - review
  - staging
  - production

variables:
  POSTGRES_DB: oral_history
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: password
  POSTGRES_HOST: postgres
  TEST_DB: oral_history
  DOCKER_DRIVER: overlay
  REGISTRY_HOST: registry.gitlab.com
  REGISTRY_URI: TODO/oral_history
  SITE_URI_BASE: TODO

build:
  stage: build
  script:
    - docker login -u "gitlab-ci-token" -p "$CI_BUILD_TOKEN" $CI_REGISTRY
    - docker build --pull -t "$CI_REGISTRY_IMAGE:$CI_PROJECT_NAME-$CI_BUILD_REF_SLUG" .
    - docker push "$CI_REGISTRY_IMAGE:$CI_PROJECT_NAME-$CI_BUILD_REF_SLUG"
  variables:
    GIT_STRATEGY: fetch
  tags:
    - docker

