version: '2.2'
services:
  postgres:
    image: postgres
    env_file:
      - .env
      - .env.development
    ports:
      - "5432"
    volumes:
      - 'postgres:/var/lib/postgresql/data'

  solr:
    image: "${REGISTRY_HOST}${REGISTRY_URI}/solr:${TAG}"
    build: solr/
    ports:
      - '8983:8983'
    volumes:
      - solr:/solr_home

  main:
    build: .
    image: "${REGISTRY_HOST}${REGISTRY_URI}:${TAG}"
    env_file:
      - .env.development
      - .env
    volumes:
      - .:/home/app/webapp

  web:
    extends: main
    # Keep the stdin open, so we can attach to our app container's process
    # and do things such as byebug, etc:
    stdin_open: true
    # Enable sending signals (CTRL+C, CTRL+P + CTRL+Q) into the container:
    tty: true
    ports:
      - "${DOCKER_PORT}"
    environment:
      - VIRTUAL_HOST=oralhistory.docker
      - VIRTUAL_PORT=80
    depends_on:
      - postgres
      - solr
      - delayed_job

  delayed_job:
    extends: main
    command: bin/delayed_job run
    depends_on:
      - postgres
      - solr

volumes:
  postgres:
  solr:
