apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "chart.fullname" . }}-env
  labels:
    {{- include "chart.labels" . | nindent 4 }}
data:
  POSTGRES_DB: {{  .Values.postgresql.database }}
  POSTGRES_PORT: "5432"
  POSTGRES_USER: {{ .Values.postgresqlUsername }}
  SOLR_ADMIN_USER: {{ .Values.solr.auth.adminUsername }}
  SOLR_COLLECTION_NAME: {{ .Values.solr.collection }}
  SOLR_PORT: "8983"
{{- range $key, $value := .Values.env.configmap }}
  {{ $key }}: "{{ $value }}"
{{- end }}
