{{- if .Values.externalsecrets.enabled -}}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "chart.fullname" . }}-externalsecret
  {{- with .Values.externalSecrets.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  refreshInterval: 10m
  secretStoreRef:
    name: {{ $.Values.externalsecrets.ref }}
    kind: ClusterSecretStore
  target:
    name: {{ $fullName }}
  data:
    {{- toYaml .Values.externalsecrets.secrets.application.data | nindent 4 }}
{{- end }}
