apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "chart.fullname" . }}-env
  labels:
    {{- include "chart.labels" . | nindent 4 }}
data:
  POSTGRES_DB: "{{ .Values.postgresql.auth.database }}"
  POSTGRES_HOST: "{{ template "chart.postgresql.host" . }}"
  POSTGRES_PORT: "{{ .Values.postgresql.service.ports.postgresql }}"
  POSTGRES_USER: "{{ .Values.postgresql.auth.username }}"
  SOLR_ADMIN_USER: "{{ .Values.web.env.SOLR_ADMIN_USER}}"
  SOLR_HOST: "{{ .Values.web.env.SOLR_HOST}}"
  SOLR_PORT: "{{ .Values.web.env.SOLR_PORT}}"
  SOLR_URL: "{{ .Values.web.env.SOLR_URL}}"
  MAKE_WAVES: "{{ .Values.web.env.MAKE_WAVES}}"
  PASSENGER_APP_ENV: "{{ .Values.web.env.PASSENGER_APP_ENV}}"
  TEST_DB: "{{ .Values.web.env.TEST_DB}}"
