apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "chart.fullname" . }}-env
  labels:
    {{- include "chart.labels" . | nindent 4 }}
data:
  POSTGRES_DB: {{  .Values.postgresql.auth.database }}
  POSTGRES_HOST: {{ template "chart.postgresql.host" . }}
  POSTGRES_PORT: "{{ .Values.postgresql.service.ports.postgresql }}"
  POSTGRES_USER: {{ .Values.postgresql.auth.username }}
  SOLR_ADMIN_USER: {{ .Values.solr.auth.adminUsername }}
  SOLR_COLLECTION_NAME: {{ .Values.solr.collection }}
  SOLR_CORE: {{ .Values.solr.coreName }}
  SOLR_HOST: {{ template "chart.solr.host" . }}
  SOLR_PORT: "8983"
  # These are used by the "web" service
  SOLR_URL: {{ .Values.web.env.SOLR_URL}}
  DEPLOY_HOOK: {{ .Values.web.env.DEPLOY_HOOK}}
  DOCKER_PORTS: "{{ .Values.web.env.DOCKER_PORTS}}"
  MAKE_WAVES: {{ .Values.web.env.MAKE_WAVES}}
  PASSENGER_APP_ENV: {{ .Values.web.env.PASSENGER_APP_ENV}}
  REGISTRY_HOST: {{ .Values.web.env.REGISTRY_HOST}}
  REGISTRY_URI: {{ .Values.web.env.REGISTRY_URI}}
  SITE_URI: {{ .Values.web.env.SITE_URI}}
  TAG: {{ .Values.web.env.TAG}}
  TEST_DB: {{ .Values.web.env.TEST_DB}}
