name: Build Oral History Web for Docker Hub
on:
  push:
    # branches:
    #   - main
  workflow_dispatch:
jobs:
  build-for-docker-hub:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Read chart yaml to get version for docker tag
        id: image-tag
        uses: KJ002/read-yaml@1.6
        with:
          file: 'charts/prod-oralhistory-values.yaml'
          key-path: '["image", "tag"]'

      - name: Report image tag
        run: echo "${{ steps.image-tag.outputs.data }}"

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: uclalibrary/oral-history:${{ steps.image-tag.outputs.data }}
