---

name: Build and Publish
on:
  push:
    branches-ignore:
      - main
      - master

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build
        id: docker_build
        uses: docker/build-push-action@v2.4.0
        with:
          tags: uclalibrary/oral-history:staging
          push: true
  jenkins:
    runs-on: ubuntu-latest
    steps:
      - name: Jenkins webhook
        # v2.1.0
        uses: joelwmale/webhook-action@fd99bb3b8272237103e349e9bb4d9b0ead9a217c
        with:
          url: 'https://${{ secrets.JENKINS_USER }}@${{ secrets.JENKINS_HOST }}/job/docker_swarm_deploy/build?token=${{ secrets.JENKINS_TOKEN }}&TERRA_ENV=${{ secrets.OH_TEST }}&cause=GitHub+action'
