---

name: Build and Publish (testing)
on:
  push:
    branches:
      - '**/test*'
      - '**test'
      - 'test**'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build
        id: docker_build
        uses: docker/build-push-action@v2.4.0
        with:
          tags: uclalibrary/oral-history:test
          push: true
      - name: Jenkins webhook
        # @master as of 2021-04-22
        uses: enflo/curl-action@fabe347922c7a9e88bafa15c4b7d6326ea802695
        with:
          curl: 'https://${{ secrets.JENKINS_USER }}@${{ secrets.JENKINS_HOST }}/job/docker_swarm_deploy/buildWithParameters?token=${{ secrets.JENKINS_TOKEN }}&TERRA_ENV=${{ secrets.OH_TEST }}&cause=GitHub+action'
